### ISSUE TITLE
REIKALAVIMAI:

### ISSUE THREAD

**Issue by liepa1** [Barakisa/Treehoot#32]
1. Creating and using your own class, struct, record and enum; - (enum nėra)
2. Property usage in struct and class; + (get/set)
3. Named and optional argument usage; - (optional neturim)
4. Extension method usage; + (servisai)
5. Iterating through collection the right way; +
6. Reading from a file using a stream; + (stage servise)
7. Create and use at least 1 generic type; +
8. Boxing and unboxing; -
9. LINQ to Objects usage (methods or queries); +
10. Implement at least one of the standard .NET interfaces (IEnumerable, IComparable, IComparer, IEquatable, IEnumerator, etc.) - (nedarysim, nes nereikia)

**Comment by Barakisa** [comment]
Creating and using your own class, struct, record and enum; - Enum padariau (Domai.Enums)
Named and optional argument usage; - Optionla padariau (*Full.cs klases)
Implement at least one of the standard .NET interfaces (IEnumerable, IComparable, IComparer, IEquatable, IEnumerator, etc.) - IComparable (Domain.PLayer)
